version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Exposes MongoDB on the default port
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin   # MongoDB root username
      - MONGO_INITDB_ROOT_PASSWORD=admin123  # MongoDB root password
      - MONGO_INITDB_DATABASE= nest  # MongoDB database name
    volumes:
      - mongo-data:/data/db  # Persists MongoDB data in a Docker volume

volumes:
  mongo-data:
    driver: local
